version: "3"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566-4583:4566-4583"
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_DEFAULT_REGION=eu-west-3
    volumes:
      - "./docker/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: foobar
    volumes:
      - "./docker/postgres:/var/lib/postgresql/data"
